"""readicionando_column_disponivel_da_entidade_area

Revision ID: 5358721a3e58
Revises: 9df787d2715a
Create Date: 2023-10-11 17:48:09.716982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5358721a3e58'
down_revision: Union[str, None] = '9df787d2715a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('disponivel', sa.Boolean(), nullable=True))
    op.drop_column('areas', 'reservada')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('reservada', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('areas', 'disponivel')
    # ### end Alembic commands ###
