"""teste2

Revision ID: 548b121cc959
Revises: 940ba087824d
Create Date: 2023-10-06 17:28:08.545650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548b121cc959'
down_revision: Union[str, None] = '940ba087824d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('iluminacao', sa.String(), nullable=True),
    sa.Column('tipo_piso', sa.String(), nullable=True),
    sa.Column('covered', sa.String(), nullable=True),
    sa.Column('foto_url', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_areas_id'), 'areas', ['id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('reserva_data', sa.DateTime(), nullable=True),
    sa.Column('hora_inicio', sa.DateTime(), nullable=True),
    sa.Column('hora_fim', sa.DateTime(), nullable=True),
    sa.Column('justificacao', sa.String(), nullable=True),
    sa.Column('reserva_tipo', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_areas_id'), table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
