"""correção_nos_imports_dos_models

Revision ID: 5cf5ef672fb7
Revises: c56f1aa53999
Create Date: 2023-11-10 10:32:28.476849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cf5ef672fb7'
down_revision: Union[str, None] = 'c56f1aa53999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('areas', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('areas', 'descricao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('areas', 'iluminacao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('areas', 'tipo_piso',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('areas', 'covered',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('areas', 'foto_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reservations', 'valor',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reservations', 'reserva_data',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('reservations', 'hora_inicio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('reservations', 'hora_fim',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('reservations', 'justificacao',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reservations', 'reserva_tipo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reservations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('reservations', 'area_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reservations', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tipouser', 'tipo',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('usuario', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('usuario', 'senha',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'senha',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('usuario', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('tipouser', 'tipo',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('reservations', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reservations', 'area_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reservations', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reservations', 'reserva_tipo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reservations', 'justificacao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reservations', 'hora_fim',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reservations', 'hora_inicio',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reservations', 'reserva_data',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('reservations', 'valor',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('areas', 'foto_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('areas', 'covered',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('areas', 'tipo_piso',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('areas', 'iluminacao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('areas', 'descricao',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('areas', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
