"""entidade_area_add_column_reservada

Revision ID: 931bc374acfa
Revises: 51dc5387141f
Create Date: 2023-10-11 13:32:55.657786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931bc374acfa'
down_revision: Union[str, None] = '51dc5387141f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('reservada', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('areas', 'reservada')
    # ### end Alembic commands ###
