"""removendo_column_disponivel_da_entidade_area

Revision ID: 9df787d2715a
Revises: 931bc374acfa
Create Date: 2023-10-11 14:27:47.465785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df787d2715a'
down_revision: Union[str, None] = '931bc374acfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('areas', 'disponivel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('disponivel', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
