"""teste4

Revision ID: c41337667b66
Revises: 5358721a3e58
Create Date: 2023-10-20 17:16:16.264572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41337667b66'
down_revision: Union[str, None] = '5358721a3e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipouser',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipouser_id'), 'tipouser', ['id'], unique=False)
    op.add_column('areas', sa.Column('usuario_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'areas', 'usuario', ['usuario_id'], ['id'])
    op.drop_column('areas', 'disponivel')
    op.drop_column('reservations', 'disponivel')
    op.add_column('usuario', sa.Column('tipo_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'usuario', 'tipouser', ['tipo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.drop_column('usuario', 'tipo_id')
    op.add_column('reservations', sa.Column('disponivel', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('areas', sa.Column('disponivel', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'areas', type_='foreignkey')
    op.drop_column('areas', 'usuario_id')
    op.drop_index(op.f('ix_tipouser_id'), table_name='tipouser')
    op.drop_table('tipouser')
    # ### end Alembic commands ###
