"""retirando ligacao entre area e usuario_id

Revision ID: c56f1aa53999
Revises: a87bad0091a7
Create Date: 2023-11-01 12:52:34.584825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56f1aa53999'
down_revision: Union[str, None] = 'a87bad0091a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('areas_usuario_id_fkey', 'areas', type_='foreignkey')
    op.drop_column('areas', 'usuario_id')
    op.drop_index('ix_tipouser_id', table_name='tipouser')
    op.alter_column('usuario', 'tipo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_usuario_id', table_name='usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_usuario_id', 'usuario', ['id'], unique=False)
    op.alter_column('usuario', 'tipo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_tipouser_id', 'tipouser', ['id'], unique=False)
    op.add_column('areas', sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('areas_usuario_id_fkey', 'areas', 'usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###
